saisie1 = input("1er nombre: ")
saisie2 = input("2ème nombre: ")
print ("La première saisie est: ", saisie1, "et la deuxième saisie est: ", saisie2)
resultat = int(saisie1) + int(saisie2)
print("Le résultat de la somme des deux saisies est: ", resultat)
